### ISSUE TITLE
OSError: access violation on BluetoothFindNextDevice

### ISSUE THREAD

**Issue by colthreepv** [joric/bluetooth-battery-monitor#1]
Just trying your project, and it breaks on this invocation

I have double checked the Struct sizes, comparing them with [win32 documentation](https://docs.microsoft.com/en-us/windows/win32/api/bluetoothapis/nf-bluetoothapis-bluetoothfindnextdevice) and they check out, so I am a short on ideas about why this breaks

System:
```
Python 3.8.0 x64
Windows 10 version 1909 18363.535
```

Full trace:
```
>python bluetooth_battery_monitor.py
Traceback (most recent call last):
  File "bluetooth_battery_monitor.py", line 314, in <module>
    main()
  File "bluetooth_battery_monitor.py", line 303, in main
    db = GetClassicDevices(db, 'class')
  File "bluetooth_battery_monitor.py", line 296, in GetClassicDevices
    if not BP.BluetoothFindNextDevice(df, byref(di)):
OSError: exception: access violation reading 0x00000000D185FEC0
```

**Comment by Kaysera** [comment]
Hi. I'm having the same problem

System:
```
Python 3.8.1 x64
Windows 10 version 1909 18363.657
```
Full trace: 
```
py .\bluetooth_battery_monitor.py
Traceback (most recent call last):
  File ".\bluetooth_battery_monitor.py", line 313, in <module>
    main()
  File ".\bluetooth_battery_monitor.py", line 302, in main
    db = GetClassicDevices(db, 'class')
  File ".\bluetooth_battery_monitor.py", line 295, in GetClassicDevices
    if not BP.BluetoothFindNextDevice(df, byref(di)):
OSError: exception: access violation reading 0x00000000A40AFFE0
```

The address seems to change every time I run the script. Any thoughts? 

Cheers.

**Comment by Anutrix** [comment]
Same issue

**Comment by medbenchohra** [comment]
Run it with Python 2.
Perhaps it needs lower than 3.8, didn't try it though.
